github actions workflow to render CV (#3)
* specify path to snakefile

* set workdir

* use conda frontend

* error if file is missing

* fix redirect

* move license file

* checkout pr branch

* 🤖 build CV

* snakemake forceall

* add xelatex to conda env

* install texlive-core from conda

* install xelatex in gha

* need sudo for apt-get in gha

* setup pixi for deps

* chore: fix typo

* update email

* bump pixi version

* for loop

* delete pixi.lock

got out of sync with pixi.toml

* fix bash conditional syntax

* ci: drop pixi cache

* create Dockerfile

* use default snakefile

* set up pixi

* chore: remove pixi.lock

* ci: install texlive fonts

* ci: more fonts

* 🤖 build CV

* enforce font, update email

* 🤖 build CV

* swap hyphen for newline cmd

* 🤖 build CV

* ignore detritus

* 🤖 build CV

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,16 +9,31 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - uses: actions/checkout@v7
-            - name: Testing
-              uses: snakemake/snakemake-github-action@v2
               with:
-                snakemake-version: "7.32.4"
-                args: "--cores 1 --use-conda"
-                show-disk-usage-on-error: true
+                ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
+            - name: install xelatex
+              run: |
+                sudo apt-get update && sudo apt-get upgrade -y && \
+                sudo apt-get install -y --no-install-recommends \
+                texlive-xetex texlive-fonts-extra texlive-fonts-recommended
+            - uses: prefix-dev/setup-pixi@v0.10.1
+              with:
+                pixi-version: v0.76.1
+                cache: false
+                activate-environment: true
+            - name: render w/ snakemake
+              run: |
+                snakemake --cores 1 --forceall
             - name: git
               run: |
-                git config --user.name "github-actions[bot]"
-                git config --user.email "41898282+github-actions[bot]@users.noreply.github.com"
+                for filename in docs/vitae_KLS.pdf docs/sound.pdf; do
+                    if [ ! -f $filename ]; then
+                        echo "File Missing: $filename"
+                        exit 1
+                    fi
+                done
+                git config user.name "github-actions[bot]"
+                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                 git add .
                 git commit -m "🤖 build CV"
                 git push
